import Fastify from 'fastify';
import { config } from './config.js';
import { requestIdPlugin } from './plugins/logger.js';
import { jwtPlugin } from './plugins/jwt.js';
import { rateLimiterPlugin } from './plugins/rateLimiter.js';
import { proxyRoutes } from './routes/proxy.js';

const app = Fastify({
  logger: {
    level: process.env.LOG_LEVEL ?? 'info',
    transport:
      process.env.NODE_ENV !== 'production'
        ? { target: 'pino-pretty', options: { colorize: true } }
        : undefined,
  },
  genReqId: () => undefined, // request IDs are generated by our plugin
  trustProxy: true,
});

// Core plugins (order matters)
await app.register(requestIdPlugin);
await app.register(jwtPlugin);
await app.register(rateLimiterPlugin);

// Proxy routes — JWT + rate-limit are enforced on all proxy paths
await app.register(proxyRoutes);

// Health check — no auth required
app.get('/health', async (_req, reply) => {
  return reply.send({ status: 'ok', ts: new Date().toISOString() });
});

try {
  await app.listen({ port: config.port, host: config.host });
} catch (err) {
  app.log.error(err);
  process.exit(1);
}
